   # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '48_cloneInstaWEbLessonApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 48_cloneInstaWEbLessonApp

        pod 'Firebase/Core'
        pod 'Firebase/Database'
        pod 'Firebase/Storage'
        pod 'Firebase/Messaging'
        pod 'Firebase/Auth'
        pod 'Firebase/Firestore'
        pod 'ActiveLabel'
        

end
